version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/var/lib/mongo/data
    expose:
      - '27017'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass

  mongo-express:
    image: mongo-express
    restart: always
    expose:
      - '8081'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: 'mongodb://mongouser:mongopass@mongo:27017/'

volumes:
  mongo-data:
