version: '3.9'

services:
  postgres-17:
    image: postgres:17-alpine
    volumes:
      - postgres17-data:/var/lib/postgresql/data
    expose:
      - '5433'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass

volumes:
  postgres17-data:
