version: '3.9'

services:
  postgres-13:
    image: postgres:13-alpine
    volumes:
      - postgres13-data:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass

volumes:
  postgres13-data:
